import type { FranchiseSource, MovieSource } from "@/lib/types";

function poster(imdbId: string) {
  return `https://images.metahub.space/poster/large/${imdbId}/img`;
}

function backdrop(imdbId: string) {
  return `https://images.metahub.space/background/medium/${imdbId}/img`;
}

function film(
  id: string,
  title: string,
  year: number,
  runtime: number,
  synopsis: string,
  imdbId: string,
  setting: string,
  chapter: string,
  tags: string[],
  note?: string,
): MovieSource {
  return {
    id,
    title,
    year,
    runtime,
    synopsis,
    poster: poster(imdbId),
    setting,
    chapter,
    tags,
    note,
  };
}

export const extraFranchises: FranchiseSource[] = [
  {
    slug: "harry-potter",
    name: "Mundo Bruxo",
    tagline: "De Nova York nos anos 20 à última batalha de Hogwarts.",
    description:
      "A cronologia do Mundo Bruxo começa com os Animais Fantásticos, décadas antes de Harry chegar ao Expresso. Os oito filmes de Hogwarts seguem o ano letivo, um depois do outro.",
    accent: "#d4af37",
    glow: "rgba(92, 24, 42, 0.72)",
    backdrop: backdrop("tt0241527"),
    orderNote:
      "Os três Animais Fantásticos acontecem entre 1926 e a década de 1930. A saga de Harry começa em 1991.",
    movies: [
      film(
        "fb-1",
        "Animais Fantásticos e Onde Habitam",
        2016,
        133,
        "Newt Scamander desembarca em Nova York com uma mala viva e acaba no meio de uma ameaça que a comunidade bruxa tenta esconder.",
        "tt3183660",
        "1926",
        "A era Grindelwald",
        [],
      ),
      film(
        "fb-2",
        "Os Crimes de Grindelwald",
        2018,
        134,
        "Grindelwald escapa e reúne seguidores em Paris. Dumbledore pede a Newt que encontre Credence antes que a guerra escolha o lado errado.",
        "tt4123430",
        "1927",
        "A era Grindelwald",
        [],
      ),
      film(
        "fb-3",
        "Os Segredos de Dumbledore",
        2022,
        142,
        "Dumbledore monta um plano discreto contra Grindelwald numa eleição que pode entregar o mundo bruxo a um discurso de pureza.",
        "tt4123432",
        "1932",
        "A era Grindelwald",
        [],
      ),
      film(
        "hp-1",
        "Harry Potter e a Pedra Filosofal",
        2001,
        152,
        "Um garoto debaixo da escada descobre que é bruxo, atravessa a plataforma 9¾ e enfrenta a primeira sombra de Voldemort em Hogwarts.",
        "tt0241527",
        "1991–1992",
        "Hogwarts",
        ["potter"],
      ),
      film(
        "hp-2",
        "Harry Potter e a Câmara Secreta",
        2002,
        161,
        "Uma voz nas paredes petrifica alunos. Harry desce à câmara e encontra um diário que ainda vai custar caro.",
        "tt0295297",
        "1992–1993",
        "Hogwarts",
        ["potter"],
      ),
      film(
        "hp-3",
        "Harry Potter e o Prisioneiro de Azkaban",
        2004,
        142,
        "Sirius Black foge de Azkaban e os dementadores cercam a escola. O tempo, literalmente, precisa ser refeito numa noite.",
        "tt0304141",
        "1993–1994",
        "Hogwarts",
        ["potter"],
      ),
      film(
        "hp-4",
        "Harry Potter e o Cálice de Fogo",
        2005,
        157,
        "O Torneio Tribruxo escolhe Harry contra a regra. A última tarefa devolve Voldemort a um corpo.",
        "tt0330373",
        "1994–1995",
        "Hogwarts",
        ["potter"],
      ),
      film(
        "hp-5",
        "Harry Potter e a Ordem da Fênix",
        2007,
        138,
        "O Ministério nega o retorno de Voldemort e ocupa Hogwarts. A Ordem da Fênix volta a se reunir no escuro.",
        "tt0373889",
        "1995–1996",
        "A guerra",
        ["potter"],
      ),
      film(
        "hp-6",
        "Harry Potter e o Enigma do Príncipe",
        2009,
        153,
        "Dumbledore prepara Harry para o que vem e abre a memória de um garoto chamado Tom. Uma torre muda o rumo da guerra.",
        "tt0417741",
        "1996–1997",
        "A guerra",
        ["potter"],
      ),
      film(
        "hp-7",
        "Harry Potter e as Relíquias da Morte: Parte 1",
        2010,
        146,
        "Sem escola e sem proteção, o trio corre atrás das horcruxes enquanto o Ministério já não é um lugar seguro.",
        "tt0926084",
        "1997",
        "A guerra",
        ["potter"],
      ),
      film(
        "hp-8",
        "Harry Potter e as Relíquias da Morte: Parte 2",
        2011,
        130,
        "A batalha chega a Hogwarts. Harry entende o que precisa fazer para que a guerra tenha um fim.",
        "tt1201607",
        "1998",
        "A guerra",
        ["potter"],
      ),
    ],
  },
  {
    slug: "terra-media",
    name: "Terra-média",
    tagline: "Do Condado de Bilbo até a queda de Barad-dûr.",
    description:
      "A cronologia da Terra-média começa com a jornada de Bilbo e só depois chega à Sociedade do Anel. A ordem de estreia fica de lado: primeiro o dragão, depois a guerra.",
    accent: "#8fbc6a",
    glow: "rgba(28, 64, 32, 0.75)",
    backdrop: backdrop("tt0120737"),
    orderNote: "Os três filmes de O Hobbit acontecem décadas antes de A Sociedade do Anel.",
    movies: [
      film(
        "hobbit-1",
        "O Hobbit: Uma Jornada Inesperada",
        2012,
        169,
        "Gandalf tira Bilbo de Bag End para uma companhia de anões. No caminho, um anel espera numa caverna.",
        "tt0903624",
        "2941 T.E.",
        "O Hobbit",
        ["ring"],
      ),
      film(
        "hobbit-2",
        "O Hobbit: A Desolação de Smaug",
        2013,
        161,
        "A companhia entra na Floresta das Trevas e chega à Montanha Solitária, onde Smaug ainda conta o ouro.",
        "tt1170358",
        "2941 T.E.",
        "O Hobbit",
        ["ring"],
      ),
      film(
        "hobbit-3",
        "O Hobbit: A Batalha dos Cinco Exércitos",
        2014,
        144,
        "Smaug cai sobre a Cidade do Lago e cinco exércitos disputam a montanha. Bilbo volta para casa com um segredo no bolso.",
        "tt2310332",
        "2941 T.E.",
        "O Hobbit",
        ["ring"],
      ),
      film(
        "lotr-1",
        "O Senhor dos Anéis: A Sociedade do Anel",
        2001,
        178,
        "Frodo herda o Um Anel e sai do Condado com oito companheiros. A sociedade se parte antes de chegar ao fim da estrada.",
        "tt0120737",
        "3018–3019 T.E.",
        "A Guerra do Anel",
        ["ring"],
      ),
      film(
        "lotr-2",
        "O Senhor dos Anéis: As Duas Torres",
        2002,
        179,
        "A sociedade segue em três caminhos. Helm's Deep aguenta a noite, e Gollum conduz Frodo para mais perto de Mordor.",
        "tt0167261",
        "3019 T.E.",
        "A Guerra do Anel",
        ["ring"],
      ),
      film(
        "lotr-3",
        "O Senhor dos Anéis: O Retorno do Rei",
        2003,
        201,
        "Gondor pede socorro, o Portão Negro se abre e Frodo chega ao fim da missão no fogo da montanha.",
        "tt0167260",
        "3019 T.E.",
        "A Guerra do Anel",
        ["ring"],
      ),
    ],
  },
  {
    slug: "jurassic",
    name: "Jurassic",
    tagline: "Da ilha de Hammond ao mundo em que os dinossauros já não cabem na cerca.",
    description:
      "A cronologia Jurassic segue a estreia porque a história também segue: o parque, a queda, e o mundo que herdou os animais. Renascimento fecha a linha.",
    accent: "#f0b429",
    glow: "rgba(120, 72, 8, 0.72)",
    backdrop: backdrop("tt0107290"),
    orderNote: "A ordem da história coincide com a de lançamento, de 1993 a 2025.",
    movies: [
      film(
        "jp-1",
        "Jurassic Park",
        1993,
        127,
        "Hammond convida especialistas para um parque de dinossauros clonados. A energia cai, e a cerca deixa de ser uma ideia.",
        "tt0107290",
        "1993",
        "O parque",
        [],
      ),
      film(
        "jp-2",
        "O Mundo Perdido: Jurassic Park",
        1997,
        129,
        "Uma segunda ilha ainda tem vida. A expedição de contenção termina com um tiranossauro nas ruas de San Diego.",
        "tt0119567",
        "1997",
        "O parque",
        [],
      ),
      film(
        "jp-3",
        "Jurassic Park III",
        2001,
        92,
        "Alan Grant volta à ilha por um resgate que lhe foi vendido como pesquisa. O espinossauro discorda do roteiro.",
        "tt0163025",
        "2001",
        "O parque",
        [],
      ),
      film(
        "jw-1",
        "Jurassic World",
        2015,
        124,
        "O parque reabre como resort. Um híbrido feito para impressionar acionistas escapa no dia de maior público.",
        "tt0369610",
        "2015",
        "O mundo",
        [],
      ),
      film(
        "jw-2",
        "Jurassic World: Reino Ameaçado",
        2018,
        128,
        "O vulcão da ilha entra em erupção e um leilão transforma os sobreviventes em mercadoria no continente.",
        "tt4881806",
        "2018",
        "O mundo",
        [],
      ),
      film(
        "jw-3",
        "Jurassic World: Domínio",
        2022,
        147,
        "Dinossauros já vivem entre cidades. Um gafanhoto de laboratório e o passado da Biosyn puxam todos para o mesmo vale.",
        "tt8041270",
        "2022",
        "O mundo",
        [],
      ),
      film(
        "jw-4",
        "Jurassic World: Renascimento",
        2025,
        133,
        "Uma equipe volta a uma ilha equatorial atrás de material genético que ainda pode valer mais do que a cerca que um dia existiu.",
        "tt31036941",
        "2025",
        "O mundo",
        [],
      ),
    ],
  },
  {
    slug: "indiana-jones",
    name: "Indiana Jones",
    tagline: "Do templo de 1935 ao relógio de 1969, na ordem da vida de Indy.",
    description:
      "A cronologia de Indiana Jones segue a biografia, não a estreia. O Templo da Perdição acontece um ano antes dos Caçadores da Arca Perdida.",
    accent: "#e07a3d",
    glow: "rgba(92, 42, 12, 0.75)",
    backdrop: backdrop("tt0082971"),
    orderNote: "Templo da Perdição se passa em 1935. Os Caçadores da Arca Perdida, em 1936.",
    movies: [
      film(
        "indy-temple",
        "Indiana Jones e o Templo da Perdição",
        1984,
        118,
        "Em 1935, Indy cai numa aldeia indiana e desce a um culto que escraviza crianças em volta de pedras sagradas.",
        "tt0087469",
        "1935",
        "Anos 30",
        [],
        "Na história, este filme vem antes de Os Caçadores da Arca Perdida.",
      ),
      film(
        "indy-raiders",
        "Os Caçadores da Arca Perdida",
        1981,
        115,
        "O governo manda Indy atrás da Arca da Aliança antes que os nazistas a abram. O chapéu e o chicote entram na lenda.",
        "tt0082971",
        "1936",
        "Anos 30",
        [],
      ),
      film(
        "indy-crusade",
        "Indiana Jones e a Última Cruzada",
        1989,
        127,
        "O pai de Indy some atrás do Santo Graal. Pai e filho atravessam a Europa com os nazistas no mesmo mapa.",
        "tt0097576",
        "1938",
        "Anos 30",
        [],
      ),
      film(
        "indy-skull",
        "Indiana Jones e o Reino da Caveira de Cristal",
        2008,
        122,
        "Em 1957, a Guerra Fria troca os nazistas por soviéticos, e uma caveira de cristal puxa Indy de volta à selva.",
        "tt0367882",
        "1957",
        "Depois da guerra",
        [],
      ),
      film(
        "indy-dial",
        "Indiana Jones e a Relíquia do Destino",
        2023,
        154,
        "Em 1969, uma antiga metade de um mecanismo de Arquimedes devolve Indy a uma corrida contra o relógio e contra o próprio tempo.",
        "tt1462764",
        "1969",
        "Depois da guerra",
        [],
      ),
    ],
  },
];
