import type { Franchise } from "@/lib/types";

export const franchises: Franchise[] = [
  {
    slug: "marvel",
    name: "Universo Marvel",
    tagline: "Do gelo da Segunda Guerra ao multiverso, na ordem em que os heróis viveram.",
    description: "A cronologia do Universo Cinematográfico Marvel segue a história, não a data de estreia. A Saga do Infinito entra inteira, com Viúva Negra no intervalo de Guerra Civil, e o Multiverso continua até o Quarteto Fantástico.",
    accent: "#e62429",
    glow: "rgba(180, 24, 32, 0.72)",
    backdrop: "https://images.metahub.space/background/medium/tt4154796/img",
    orderNote: "Ordem interna da história. Longe de Casa fecha a Saga do Infinito mesmo aparecendo depois de Shang-Chi e Eternos no calendário.",
    movies: [
    {
      id: "mcu-tfa",
      title: "Capitão América: O Primeiro Vingador",
      year: 2011,
      runtime: 124,
      synopsis: "Steve Rogers deixa o Brooklyn, vira o supersoldado da guerra e some no gelo com um escudo que ainda vai mudar o século.",
      poster: "https://images.metahub.space/poster/large/tt0458339/img",
      setting: "1943–1945",
      chapter: "Antes dos Vingadores",
      tags: ["infinity"],
    },
    {
      id: "mcu-marvel",
      title: "Capitã Marvel",
      year: 2019,
      runtime: 123,
      synopsis: "Carol Danvers cai na Terra dos anos 90, descobre quem apagou a memória dela e escolhe de que lado fica a guerra kree.",
      poster: "https://images.metahub.space/poster/large/tt4154664/img",
      setting: "1995",
      chapter: "Antes dos Vingadores",
      tags: ["infinity"],
    },
    {
      id: "mcu-iron",
      title: "Homem de Ferro",
      year: 2008,
      runtime: 126,
      synopsis: "Tony Stark constrói a armadura numa caverna e volta para casa decidido a desmontar o império de armas que levava o seu nome.",
      poster: "https://images.metahub.space/poster/large/tt0371746/img",
      setting: "2010",
      chapter: "Antes dos Vingadores",
      tags: ["infinity"],
    },
    {
      id: "mcu-iron2",
      title: "Homem de Ferro 2",
      year: 2010,
      runtime: 124,
      synopsis: "O paládio envenena Tony enquanto Vanko e o governo disputam a tecnologia da armadura. Nick Fury já observa de longe.",
      poster: "https://images.metahub.space/poster/large/tt1228705/img",
      setting: "2011",
      chapter: "Antes dos Vingadores",
      tags: ["infinity"],
    },
    {
      id: "mcu-hulk",
      title: "O Incrível Hulk",
      year: 2008,
      runtime: 112,
      synopsis: "Bruce Banner foge do exército e de si mesmo, até um soro rival transformar a caçada numa luta de monstros em Harlem.",
      poster: "https://images.metahub.space/poster/large/tt0800080/img",
      setting: "2011",
      chapter: "Antes dos Vingadores",
      tags: ["infinity"],
    },
    {
      id: "mcu-thor",
      title: "Thor",
      year: 2011,
      runtime: 115,
      synopsis: "O herdeiro de Asgard é banido para o Novo México e só volta a merecer o martelo quando deixa de tratar a Terra como quintal.",
      poster: "https://images.metahub.space/poster/large/tt0800369/img",
      setting: "2011",
      chapter: "Antes dos Vingadores",
      tags: ["infinity"],
    },
    {
      id: "mcu-avengers",
      title: "Os Vingadores",
      year: 2012,
      runtime: 143,
      synopsis: "Loki abre um portal sobre Nova York e obriga um time que mal se suporta a defender a cidade junto.",
      poster: "https://images.metahub.space/poster/large/tt0848228/img",
      setting: "2012",
      chapter: "Antes dos Vingadores",
      tags: ["infinity"],
    },
    {
      id: "mcu-iron3",
      title: "Homem de Ferro 3",
      year: 2013,
      runtime: 130,
      synopsis: "Depois de Nova York, Tony não dorme. O Mandarim vira desculpa para ele descobrir se ainda é alguém sem a armadura.",
      poster: "https://images.metahub.space/poster/large/tt1300854/img",
      setting: "2012",
      chapter: "Saga do Infinito",
      tags: ["infinity"],
    },
    {
      id: "mcu-tdw",
      title: "Thor: O Mundo Sombrio",
      year: 2013,
      runtime: 112,
      synopsis: "Jane encontra o Aether e Malekith tenta devolver o universo à escuridão. Thor atravessa os reinos para impedi-lo.",
      poster: "https://images.metahub.space/poster/large/tt1981115/img",
      setting: "2013",
      chapter: "Saga do Infinito",
      tags: ["infinity"],
    },
    {
      id: "mcu-ws",
      title: "Capitão América: O Soldado Invernal",
      year: 2014,
      runtime: 136,
      synopsis: "Steve descobre que a S.H.I.E.L.D. foi comida por dentro e que o fantasma que o caça tem o rosto de Bucky.",
      poster: "https://images.metahub.space/poster/large/tt1843866/img",
      setting: "2014",
      chapter: "Saga do Infinito",
      tags: ["infinity"],
    },
    {
      id: "mcu-gotg",
      title: "Guardiões da Galáxia",
      year: 2014,
      runtime: 121,
      synopsis: "Um ladrão da Terra, uma assassina, um lutador sem metáforas e dois comparsas herdam uma pedra que Ronan quer para Thanos.",
      poster: "https://images.metahub.space/poster/large/tt2015381/img",
      setting: "2014",
      chapter: "Saga do Infinito",
      tags: ["infinity"],
    },
    {
      id: "mcu-gotg2",
      title: "Guardiões da Galáxia Vol. 2",
      year: 2017,
      runtime: 136,
      synopsis: "Meses depois da primeira aventura, Peter encontra o pai celeste e a equipe descobre que família não é quem compartilha o sangue.",
      poster: "https://images.metahub.space/poster/large/tt3896198/img",
      setting: "2014",
      chapter: "Saga do Infinito",
      tags: ["infinity"],
    },
    {
      id: "mcu-ultron",
      title: "Vingadores: Era de Ultron",
      year: 2015,
      runtime: 141,
      synopsis: "Tony tenta aposentar os Vingadores com uma inteligência artificial. Ultron discorda e Sokovia paga a conta.",
      poster: "https://images.metahub.space/poster/large/tt2395427/img",
      setting: "2015",
      chapter: "Saga do Infinito",
      tags: ["infinity"],
    },
    {
      id: "mcu-antman",
      title: "Homem-Formiga",
      year: 2015,
      runtime: 117,
      synopsis: "Scott Lang sai da cadeia direto para um traje que encolhe o corpo e complica o assalto que deveria ser simples.",
      poster: "https://images.metahub.space/poster/large/tt0478970/img",
      setting: "2015",
      chapter: "Saga do Infinito",
      tags: ["infinity"],
    },
    {
      id: "mcu-cw",
      title: "Capitão América: Guerra Civil",
      year: 2016,
      runtime: 147,
      synopsis: "Os Acordos de Sokovia racham o time. Steve escolhe Bucky. Tony escolhe a lei. O aeroporto vira campo de batalha.",
      poster: "https://images.metahub.space/poster/large/tt3498820/img",
      setting: "2016",
      chapter: "Saga do Infinito",
      tags: ["infinity"],
    },
    {
      id: "mcu-widow",
      title: "Viúva Negra",
      year: 2021,
      runtime: 134,
      synopsis: "Entre Guerra Civil e a Guerra Infinita, Natasha acerta as contas com a Sala Vermelha e com a família que nunca foi de verdade.",
      poster: "https://images.metahub.space/poster/large/tt3480822/img",
      setting: "2016",
      chapter: "Saga do Infinito",
      tags: [],
      note: "A história se passa logo depois de Guerra Civil, embora o filme tenha estreado anos mais tarde.",
    },
    {
      id: "mcu-panther",
      title: "Pantera Negra",
      year: 2018,
      runtime: 134,
      synopsis: "T'Challa volta a Wakanda para a coroa e encontra em Killmonger a pergunta que o trono não quer ouvir.",
      poster: "https://images.metahub.space/poster/large/tt1825683/img",
      setting: "2016",
      chapter: "Saga do Infinito",
      tags: ["infinity"],
    },
    {
      id: "mcu-home",
      title: "Homem-Aranha: De Volta ao Lar",
      year: 2017,
      runtime: 133,
      synopsis: "Peter Parker tenta ser herói de bairro enquanto o Abutre recicla a tecnologia deixada pela batalha de Nova York.",
      poster: "https://images.metahub.space/poster/large/tt2250912/img",
      setting: "2016",
      chapter: "Saga do Infinito",
      tags: ["infinity"],
    },
    {
      id: "mcu-strange",
      title: "Doutor Estranho",
      year: 2016,
      runtime: 115,
      synopsis: "Um cirurgião sem as mãos aprende em Kamar-Taj que o universo tem mais portas do que o ego dele suportava.",
      poster: "https://images.metahub.space/poster/large/tt1211837/img",
      setting: "2016–2017",
      chapter: "Saga do Infinito",
      tags: ["infinity"],
    },
    {
      id: "mcu-ragnarok",
      title: "Thor: Ragnarok",
      year: 2017,
      runtime: 130,
      synopsis: "Hela toma Asgard, Thor vira gladiador em Sakaar e o fim do reino vira o único jeito de salvar o povo.",
      poster: "https://images.metahub.space/poster/large/tt3501632/img",
      setting: "2017",
      chapter: "Saga do Infinito",
      tags: ["infinity"],
    },
    {
      id: "mcu-wasp",
      title: "Homem-Formiga e a Vespa",
      year: 2018,
      runtime: 118,
      synopsis: "Scott e Hope descem ao reino quântico para resgatar Janet, enquanto o mundo lá fora já começa a desaparecer.",
      poster: "https://images.metahub.space/poster/large/tt5095030/img",
      setting: "2018",
      chapter: "Saga do Infinito",
      tags: ["infinity"],
      note: "A trama principal acontece pouco antes do estalo. A cena final já é durante Guerra Infinita.",
    },
    {
      id: "mcu-iw",
      title: "Vingadores: Guerra Infinita",
      year: 2018,
      runtime: 149,
      synopsis: "Thanos coleta as joias uma a uma. Os heróis chegam tarde em quase todas as frentes, e o estalo corta o universo pela metade.",
      poster: "https://images.metahub.space/poster/large/tt4154756/img",
      setting: "2018",
      chapter: "Saga do Infinito",
      tags: ["infinity"],
    },
    {
      id: "mcu-endgame",
      title: "Vingadores: Ultimato",
      year: 2019,
      runtime: 181,
      synopsis: "Cinco anos depois do estalo, quem sobrou aposta numa viagem no tempo impossível para trazer de volta quem virou pó.",
      poster: "https://images.metahub.space/poster/large/tt4154796/img",
      setting: "2023",
      chapter: "Saga do Infinito",
      tags: ["infinity"],
    },
    {
      id: "mcu-shang",
      title: "Shang-Chi e a Lenda dos Dez Anéis",
      year: 2021,
      runtime: 132,
      synopsis: "Um manobrista em São Francisco é puxado de volta para o pai, os dez anéis e um vilarejo que não deveria existir.",
      poster: "https://images.metahub.space/poster/large/tt9376612/img",
      setting: "2024",
      chapter: "Multiverso",
      tags: [],
    },
    {
      id: "mcu-eternals",
      title: "Eternos",
      year: 2021,
      runtime: 156,
      synopsis: "Seres plantados na Terra há milênios acordam para uma emergência: o planeta que protegeram está prestes a nascer como um celestial.",
      poster: "https://images.metahub.space/poster/large/tt9032400/img",
      setting: "2024",
      chapter: "Multiverso",
      tags: [],
    },
    {
      id: "mcu-ffh",
      title: "Homem-Aranha: Longe de Casa",
      year: 2019,
      runtime: 129,
      synopsis: "No verão depois do retorno, Peter quer férias na Europa. Mysterio oferece um espetáculo e fica com o lugar de Tony.",
      poster: "https://images.metahub.space/poster/large/tt6320628/img",
      setting: "2024",
      chapter: "Multiverso",
      tags: ["infinity"],
      note: "Epílogo da Saga do Infinito, mesmo com Shang-Chi e Eternos acontecendo antes neste calendário.",
    },
    {
      id: "mcu-nwh",
      title: "Homem-Aranha: Sem Volta para Casa",
      year: 2021,
      runtime: 148,
      synopsis: "Um feitiço para apagar a identidade de Peter racha o multiverso e traz vilões — e outros Aranhas — para a mesma Nova York.",
      poster: "https://images.metahub.space/poster/large/tt10872600/img",
      setting: "2024",
      chapter: "Multiverso",
      tags: [],
    },
    {
      id: "mcu-mom",
      title: "Doutor Estranho no Multiverso da Loucura",
      year: 2022,
      runtime: 126,
      synopsis: "Wanda atravessa universos atrás dos filhos que sonhou, e Strange tenta impedir que uma adolescente pague essa conta.",
      poster: "https://images.metahub.space/poster/large/tt9419884/img",
      setting: "2024",
      chapter: "Multiverso",
      tags: [],
    },
    {
      id: "mcu-lat",
      title: "Thor: Amor e Trovão",
      year: 2022,
      runtime: 119,
      synopsis: "Gorr quer o fim dos deuses. Jane empunha o Mjolnir, e Thor precisa decidir que tipo de rei ainda consegue ser.",
      poster: "https://images.metahub.space/poster/large/tt10648342/img",
      setting: "2025",
      chapter: "Multiverso",
      tags: [],
    },
    {
      id: "mcu-wf",
      title: "Pantera Negra: Wakanda para Sempre",
      year: 2022,
      runtime: 161,
      synopsis: "Wakanda chora T'Challa enquanto Talokan sobe do mar e Shuri precisa escolher o que fazer com a raiva.",
      poster: "https://images.metahub.space/poster/large/tt9114286/img",
      setting: "2025",
      chapter: "Multiverso",
      tags: [],
    },
    {
      id: "mcu-quantum",
      title: "Homem-Formiga e a Vespa: Quantumania",
      year: 2023,
      runtime: 124,
      synopsis: "A família Lang é sugada para o reino quântico e encontra Kang, um conquistador que já perdeu e ainda não acabou.",
      poster: "https://images.metahub.space/poster/large/tt10954600/img",
      setting: "2025",
      chapter: "Multiverso",
      tags: [],
    },
    {
      id: "mcu-gotg3",
      title: "Guardiões da Galáxia Vol. 3",
      year: 2023,
      runtime: 150,
      synopsis: "Rocket é caçado pelo criador que o montou. A equipe faz a última missão juntos para salvar quem sempre segurou o volante.",
      poster: "https://images.metahub.space/poster/large/tt6791350/img",
      setting: "2025",
      chapter: "Multiverso",
      tags: [],
    },
    {
      id: "mcu-marvels",
      title: "As Marvels",
      year: 2023,
      runtime: 105,
      synopsis: "Os poderes de Carol, Monica e Kamala trocam de lugar. Uma guerra kree empurra as três para a mesma luta.",
      poster: "https://images.metahub.space/poster/large/tt10676048/img",
      setting: "2025",
      chapter: "Multiverso",
      tags: [],
    },
    {
      id: "mcu-deadpool",
      title: "Deadpool & Wolverine",
      year: 2024,
      runtime: 128,
      synopsis: "Wade invade a linha do tempo da TVA para achar um Wolverine capaz de impedir que o seu universo seja apagado.",
      poster: "https://images.metahub.space/poster/large/tt6263850/img",
      setting: "2024",
      chapter: "Multiverso",
      tags: [],
    },
    {
      id: "mcu-bnw",
      title: "Capitão América: Admirável Mundo Novo",
      year: 2025,
      runtime: 118,
      synopsis: "Sam Wilson carrega o escudo para uma mesa em que o presidente Ross e uma conspiração antiga não pediram licença.",
      poster: "https://images.metahub.space/poster/large/tt14513804/img",
      setting: "2026",
      chapter: "Multiverso",
      tags: [],
    },
    {
      id: "mcu-thunder",
      title: "Thunderbolts*",
      year: 2025,
      runtime: 126,
      synopsis: "Agentes descartáveis são trancados no mesmo buraco e descobrem que a missão era se eliminarem. O asterisco importa.",
      poster: "https://images.metahub.space/poster/large/tt20969586/img",
      setting: "2026",
      chapter: "Multiverso",
      tags: [],
    },
    {
      id: "mcu-ff",
      title: "Quarteto Fantástico: Primeiros Passos",
      year: 2025,
      runtime: 115,
      synopsis: "Numa Terra paralela, Reed, Sue, Johnny e Ben enfrentam a primeira ameaça cósmica de um mundo que ainda os trata como família famosa.",
      poster: "https://images.metahub.space/poster/large/tt10676052/img",
      setting: "Anos 1960",
      chapter: "Multiverso",
      tags: [],
      note: "Ambientado no universo 828, uma Terra retrô dos anos 1960, fora da linha principal do MCU.",
    }
    ],
  },
  {
    slug: "velozes",
    name: "Velozes e Furiosos",
    tagline: "Da corrida de rua em Los Angeles até o mundo inteiro — com Tóquio no lugar certo.",
    description: "A saga de Dom, Brian, Letty e a família que foi se juntando no caminho. A ordem aqui é a da história: Desafio em Tóquio só entra depois de Velozes 6, porque é lá que Han encontra o fim que os filmes seguintes ainda não tinham mostrado.",
    accent: "#ff7a18",
    glow: "rgba(180, 70, 10, 0.72)",
    backdrop: "https://images.metahub.space/background/medium/tt2820852/img",
    orderNote: "Ordem narrativa da família Toretto. Tóquio fica entre o sexto e o sétimo filme. Hobbs & Shaw é o spin-off entre o oitavo e o nono.",
    movies: [
    {
      id: "fast-1",
      title: "Velozes e Furiosos",
      year: 2001,
      runtime: 106,
      synopsis: "Brian infiltra o circuito de corridas de Los Angeles e acaba do lado de Dom na hora em que deveria algemá-lo.",
      poster: "https://images.metahub.space/poster/large/tt0232500/img",
      setting: "2001",
      chapter: "As ruas",
      tags: ["fast-main"],
    },
    {
      id: "fast-2",
      title: "+ Velozes + Furiosos",
      year: 2003,
      runtime: 107,
      synopsis: "Fora da polícia, Brian corre em Miami com Roman Pearce para chegar a um cartel antes que o disfarce desmanche.",
      poster: "https://images.metahub.space/poster/large/tt0322259/img",
      setting: "2003",
      chapter: "As ruas",
      tags: ["fast-main"],
    },
    {
      id: "fast-4",
      title: "Velozes e Furiosos 4",
      year: 2009,
      runtime: 107,
      synopsis: "A morte de Letty puxa Dom de volta. Brian, agora agente, cruza com ele numa caçada que os dois fazem por contas diferentes.",
      poster: "https://images.metahub.space/poster/large/tt1013752/img",
      setting: "2009",
      chapter: "As ruas",
      tags: ["fast-main"],
    },
    {
      id: "fast-5",
      title: "Velozes e Furiosos 5: Operação Rio",
      year: 2011,
      runtime: 130,
      synopsis: "No Rio, o golpe contra um empresário corrupto vira a virada da saga: a equipe cresce e Hobbs entra na perseguição.",
      poster: "https://images.metahub.space/poster/large/tt1596343/img",
      setting: "2010",
      chapter: "A família",
      tags: ["fast-main"],
    },
    {
      id: "fast-6",
      title: "Velozes e Furiosos 6",
      year: 2013,
      runtime: 130,
      synopsis: "Hobbs oferece anistia se a família parar Shaw. Letty está viva, sem memória, do outro lado da pista.",
      poster: "https://images.metahub.space/poster/large/tt1905041/img",
      setting: "2013",
      chapter: "A família",
      tags: ["fast-main"],
    },
    {
      id: "fast-tokyo",
      title: "Velozes e Furiosos: Desafio em Tóquio",
      year: 2006,
      runtime: 104,
      synopsis: "Sean aprende a driftar em Tóquio e Han segura o mundo noturno — até o acidente que a saga inteira ainda ia explicar.",
      poster: "https://images.metahub.space/poster/large/tt0463985/img",
      setting: "2014",
      chapter: "A família",
      tags: ["fast-main"],
      note: "Na história, este filme acontece depois de Velozes 6. É aqui que Han chega a Tóquio.",
    },
    {
      id: "fast-7",
      title: "Velozes e Furiosos 7",
      year: 2015,
      runtime: 137,
      synopsis: "Deckard Shaw quer vingança pelo irmão. A família atravessa o planeta e paga um preço que não volta atrás.",
      poster: "https://images.metahub.space/poster/large/tt2820852/img",
      setting: "2014",
      chapter: "A família",
      tags: ["fast-main"],
    },
    {
      id: "fast-8",
      title: "Velozes e Furiosos 8",
      year: 2017,
      runtime: 136,
      synopsis: "Dom vira as costas para a equipe. Cipher tem uma alavanca, e Hobbs precisa correr atrás de quem sempre foi o centro.",
      poster: "https://images.metahub.space/poster/large/tt4630562/img",
      setting: "2017",
      chapter: "O mundo",
      tags: ["fast-main"],
    },
    {
      id: "fast-hobbs",
      title: "Hobbs & Shaw",
      year: 2019,
      runtime: 136,
      synopsis: "O agente e o vilão reformado são obrigados a dividir a missão contra um terrorista melhorado por tecnologia.",
      poster: "https://images.metahub.space/poster/large/tt6806448/img",
      setting: "2019",
      chapter: "O mundo",
      tags: ["spinoff"],
    },
    {
      id: "fast-9",
      title: "Velozes e Furiosos 9",
      year: 2021,
      runtime: 143,
      synopsis: "O irmão que Dom deixou para trás volta com um plano, e o passado da família empurra a corrida para além do asfalto.",
      poster: "https://images.metahub.space/poster/large/tt5433138/img",
      setting: "2020",
      chapter: "O mundo",
      tags: ["fast-main"],
    },
    {
      id: "fast-10",
      title: "Velozes e Furiosos 10",
      year: 2023,
      runtime: 141,
      synopsis: "Dante, filho do homem que a equipe derrubou no Rio, transforma a vingança num jogo em que ninguém corre no mesmo carro.",
      poster: "https://images.metahub.space/poster/large/tt5433140/img",
      setting: "2022",
      chapter: "O mundo",
      tags: ["fast-main"],
    }
    ],
  },
  {
    slug: "star-wars",
    name: "Star Wars",
    tagline: "Da queda da República ao último Skywalker, com as histórias solo no meio do caminho.",
    description: "A cronologia da galáxia começa no Episódio I, atravessa o Império com Solo e Rogue One, e só então chega à trilogia clássica e à sequência. A ordem de estreia fica de lado: aqui vale o calendário da saga.",
    accent: "#ffe81f",
    glow: "rgba(120, 100, 10, 0.72)",
    backdrop: "https://images.metahub.space/background/medium/tt0076759/img",
    orderNote: "Ordem da história galáctica. Solo fica entre a vingança dos Sith e Rogue One. Rogue One termina minutos antes de Uma Nova Esperança.",
    movies: [
    {
      id: "sw-ep1",
      title: "Episódio I: A Ameaça Fantasma",
      year: 1999,
      runtime: 136,
      synopsis: "Dois jedi escoltam uma rainha, descobrem Anakin em Tatooine e veem o Senado começar a apodrecer sob um sorriso.",
      poster: "https://images.metahub.space/poster/large/tt0120915/img",
      setting: "32 ABY",
      chapter: "A queda da República",
      tags: ["skywalker"],
    },
    {
      id: "sw-ep2",
      title: "Episódio II: Ataque dos Clones",
      year: 2002,
      runtime: 142,
      synopsis: "O amor proibido de Anakin e Padmé cresce enquanto a República ganha um exército que já nasceu com dono.",
      poster: "https://images.metahub.space/poster/large/tt0121765/img",
      setting: "22 ABY",
      chapter: "A queda da República",
      tags: ["skywalker"],
    },
    {
      id: "sw-ep3",
      title: "Episódio III: A Vingança dos Sith",
      year: 2005,
      runtime: 140,
      synopsis: "A guerra acaba do jeito que Palpatine desenhou. Anakin cai, a Ordem Jedi queima e Luke e Leia são separados.",
      poster: "https://images.metahub.space/poster/large/tt0121766/img",
      setting: "19 ABY",
      chapter: "A queda da República",
      tags: ["skywalker"],
    },
    {
      id: "sw-solo",
      title: "Han Solo: Uma História Star Wars",
      year: 2018,
      runtime: 135,
      synopsis: "Um contrabandista ainda sem fama conhece Chewbacca, ganha o Millennium Falcon de Lando e faz o primeiro desvio de Kessel.",
      poster: "https://images.metahub.space/poster/large/tt3778644/img",
      setting: "13–10 ABY",
      chapter: "A era do Império",
      tags: [],
    },
    {
      id: "sw-rogue",
      title: "Rogue One: Uma História Star Wars",
      year: 2016,
      runtime: 133,
      synopsis: "Jyn Erso e um esquadrão sem nome roubam os planos da Estrela da Morte. A vitória dura o tempo de uma transmissão.",
      poster: "https://images.metahub.space/poster/large/tt3748528/img",
      setting: "0 ABY",
      chapter: "A era do Império",
      tags: [],
      note: "Termina imediatamente antes de Uma Nova Esperança.",
    },
    {
      id: "sw-anh",
      title: "Episódio IV: Uma Nova Esperança",
      year: 1977,
      runtime: 121,
      synopsis: "Uma fazendeira de Tatooine vira a última esperança da Aliança quando os planos da Estrela da Morte caem nas mãos certas.",
      poster: "https://images.metahub.space/poster/large/tt0076759/img",
      setting: "0 ABY",
      chapter: "A era do Império",
      tags: ["skywalker"],
    },
    {
      id: "sw-esb",
      title: "Episódio V: O Império Contra-Ataca",
      year: 1980,
      runtime: 124,
      synopsis: "Hoth cai, Dagobah ensina pouco e devagar, e em Bespin a verdade sobre o pai de Luke corta mais do que o sabre.",
      poster: "https://images.metahub.space/poster/large/tt0080684/img",
      setting: "3 DBY",
      chapter: "A era do Império",
      tags: ["skywalker"],
    },
    {
      id: "sw-rotj",
      title: "Episódio VI: O Retorno de Jedi",
      year: 1983,
      runtime: 131,
      synopsis: "O resgate de Han, a lua de Endor e o trono do Imperador fecham a guerra com uma escolha que Anakin ainda consegue fazer.",
      poster: "https://images.metahub.space/poster/large/tt0086190/img",
      setting: "4 DBY",
      chapter: "A era do Império",
      tags: ["skywalker"],
    },
    {
      id: "sw-tfa",
      title: "Episódio VII: O Despertar da Força",
      year: 2015,
      runtime: 136,
      synopsis: "Uma catadora de Jakku, um stormtrooper desertor e a busca por Luke acordam a guerra que a galáxia achou que tinha enterrado.",
      poster: "https://images.metahub.space/poster/large/tt2488496/img",
      setting: "34 DBY",
      chapter: "A nova Resistência",
      tags: ["skywalker"],
    },
    {
      id: "sw-tlj",
      title: "Episódio VIII: Os Últimos Jedi",
      year: 2017,
      runtime: 152,
      synopsis: "A Resistência foge com o combustível contado. Rey procura um mestre que não quer sê-lo, e Kylo oferece um trono a dois.",
      poster: "https://images.metahub.space/poster/large/tt2527338/img",
      setting: "34 DBY",
      chapter: "A nova Resistência",
      tags: ["skywalker"],
    },
    {
      id: "sw-tros",
      title: "Episódio IX: A Ascensão Skywalker",
      year: 2019,
      runtime: 142,
      synopsis: "Palpatine volta do escuro, a Resistência procura um caminho até Exegol e Rey decide que sobrenome se carrega por escolha.",
      poster: "https://images.metahub.space/poster/large/tt2527336/img",
      setting: "35 DBY",
      chapter: "A nova Resistência",
      tags: ["skywalker"],
    }
    ],
  },
  {
    slug: "dceu",
    name: "Universo DC",
    tagline: "Deuses, vigilantes e esquadrões, do front da Primeira Guerra ao fim do reino de Atlantis.",
    description: "O Universo Estendido da DC na ordem em que os fatos se encadeiam: as duas Mulheres-Maravilha abrem o século, o Homem de Aço chega depois, e o crepúsculo da saga passa por The Flash até o Reino Perdido.",
    accent: "#5b8cff",
    glow: "rgba(30, 70, 170, 0.72)",
    backdrop: "https://images.metahub.space/background/medium/tt0451279/img",
    orderNote: "Ordem interna, não a de lançamento. Aves de Rapina entra depois do Esquadrão Suicida. Liga da Justiça é o corte lançado nos cinemas em 2017.",
    movies: [
    {
      id: "dceu-ww",
      title: "Mulher-Maravilha",
      year: 2017,
      runtime: 141,
      synopsis: "Diana deixa Themyscira na Primeira Guerra acreditando que matar Ares acaba com a violência dos homens.",
      poster: "https://images.metahub.space/poster/large/tt0451279/img",
      setting: "1918",
      chapter: "Origens",
      tags: [],
    },
    {
      id: "dceu-ww84",
      title: "Mulher-Maravilha 1984",
      year: 2020,
      runtime: 151,
      synopsis: "Em Washington dos anos 80, uma pedra que realiza desejos devolve Steve e entrega o mundo a um apresentador ambicioso.",
      poster: "https://images.metahub.space/poster/large/tt7126948/img",
      setting: "1984",
      chapter: "Origens",
      tags: [],
    },
    {
      id: "dceu-mos",
      title: "O Homem de Aço",
      year: 2013,
      runtime: 143,
      synopsis: "Clark esconde o que é até Zod chegar. A escolha de revelar Superman também é a escolha de quanto da cidade sobrevive.",
      poster: "https://images.metahub.space/poster/large/tt0770828/img",
      setting: "2013",
      chapter: "Origens",
      tags: [],
    },
    {
      id: "dceu-bvs",
      title: "Batman vs Superman: A Origem da Justiça",
      year: 2016,
      runtime: 151,
      synopsis: "Bruce vê um deus no meio de Metrópolis e decide que alguém precisa poder derrubá-lo. Lex junta os dois no mesmo tabuleiro.",
      poster: "https://images.metahub.space/poster/large/tt2975590/img",
      setting: "2015",
      chapter: "A Liga",
      tags: [],
    },
    {
      id: "dceu-ss",
      title: "Esquadrão Suicida",
      year: 2016,
      runtime: 123,
      synopsis: "Waller monta um time de presos com bombas no pescoço. Amanda não quer heróis. Quer gente que possa negar.",
      poster: "https://images.metahub.space/poster/large/tt1386697/img",
      setting: "2016",
      chapter: "A Liga",
      tags: [],
    },
    {
      id: "dceu-bop",
      title: "Aves de Rapina",
      year: 2020,
      runtime: 109,
      synopsis: "Harley sem Coringa vira alvo de Gotham. Caçadora, Canário e Montoya cruzam o mesmo diamante e o mesmo policial.",
      poster: "https://images.metahub.space/poster/large/tt7713068/img",
      setting: "2016",
      chapter: "A Liga",
      tags: [],
    },
    {
      id: "dceu-jl",
      title: "Liga da Justiça",
      year: 2017,
      runtime: 120,
      synopsis: "Com Superman morto, Bruce e Diana reúnem um time às pressas contra Steppenwolf e as Caixas Maternas.",
      poster: "https://images.metahub.space/poster/large/tt0974015/img",
      setting: "2017",
      chapter: "A Liga",
      tags: [],
      note: "Duração do corte teatral de 2017.",
    },
    {
      id: "dceu-aqua",
      title: "Aquaman",
      year: 2018,
      runtime: 143,
      synopsis: "Arthur volta ao mar para disputar o trono com Orm antes que Atlantis declare guerra à superfície.",
      poster: "https://images.metahub.space/poster/large/tt1477834/img",
      setting: "2018",
      chapter: "A Liga",
      tags: [],
    },
    {
      id: "dceu-shazam",
      title: "Shazam!",
      year: 2019,
      runtime: 132,
      synopsis: "Um garoto de Filadélfia ganha o corpo de um campeão e descobre que o vilão também foi uma criança deixada para trás.",
      poster: "https://images.metahub.space/poster/large/tt0448115/img",
      setting: "2018",
      chapter: "A Liga",
      tags: [],
    },
    {
      id: "dceu-tss",
      title: "O Esquadrão Suicida",
      year: 2021,
      runtime: 132,
      synopsis: "Outra leva de condenados desembarca em Corto Maltese. A missão oficial é fachada para o que Starro esconde.",
      poster: "https://images.metahub.space/poster/large/tt6334354/img",
      setting: "2021",
      chapter: "Crepúsculo",
      tags: [],
    },
    {
      id: "dceu-adam",
      title: "Adão Negro",
      year: 2022,
      runtime: 125,
      synopsis: "Kahndaq acorda um campeão antigo que não pede licença à Sociedade da Justiça para reescrever quem manda.",
      poster: "https://images.metahub.space/poster/large/tt6443346/img",
      setting: "2022",
      chapter: "Crepúsculo",
      tags: [],
    },
    {
      id: "dceu-shazam2",
      title: "Shazam! Fúria dos Deuses",
      year: 2023,
      runtime: 130,
      synopsis: "As filhas de Atlas querem o cajado de volta. A família de Billy precisa ser equipe de verdade, não só um relâmpago.",
      poster: "https://images.metahub.space/poster/large/tt10151854/img",
      setting: "2022",
      chapter: "Crepúsculo",
      tags: [],
    },
    {
      id: "dceu-flash",
      title: "The Flash",
      year: 2023,
      runtime: 144,
      synopsis: "Barry corre para salvar a mãe e racha o tempo. No universo que sobra, o Batman é outro e o general Zod ainda chega.",
      poster: "https://images.metahub.space/poster/large/tt0439572/img",
      setting: "2023",
      chapter: "Crepúsculo",
      tags: [],
    },
    {
      id: "dceu-beetle",
      title: "Besouro Azul",
      year: 2023,
      runtime: 127,
      synopsis: "Jaime Reyes volta para Palmera City e um escaravelho alienígena escolhe a família dele como campo de batalha.",
      poster: "https://images.metahub.space/poster/large/tt9362930/img",
      setting: "2023",
      chapter: "Crepúsculo",
      tags: [],
    },
    {
      id: "dceu-aqua2",
      title: "Aquaman 2: O Reino Perdido",
      year: 2023,
      runtime: 124,
      synopsis: "Arthur precisa do irmão que prendeu para impedir que o Tridente Negro acenda uma ameaça antiga debaixo d'água.",
      poster: "https://images.metahub.space/poster/large/tt9663764/img",
      setting: "2023",
      chapter: "Crepúsculo",
      tags: [],
    }
    ],
  }
];

export function getFranchise(slug: string) {
  return franchises.find((franchise) => franchise.slug === slug);
}
