import type { Soundtrack } from "@/lib/types";

export const soundtracks: Record<string, Soundtrack> = {
  "mcu-tfa": { title: "Star Spangled Man", artist: "Alan Silvestri", youtubeId: "tfgbpqp7yIs" },
  "mcu-marvel": { title: "Captain Marvel", artist: "Pinar Toprak", youtubeId: "KNxOirM9ZFI" },
  "mcu-iron": { title: "Iron Man", artist: "Ramin Djawadi", youtubeId: "svjDuZRaSLQ" },
  "mcu-iron2": { title: "Make Way for Tomorrow Today", artist: "John Debney", youtubeId: "preBdo4NLvU" },
  "mcu-hulk": { title: "The Incredible Hulk", artist: "Craig Armstrong", youtubeId: "1oiG8KmKpqo" },
  "mcu-thor": { title: "Thor", artist: "Patrick Doyle", youtubeId: "SuxCmC9GRqc" },
  "mcu-avengers": { title: "The Avengers", artist: "Alan Silvestri", youtubeId: "XNCQZ0wxphY" },
  "mcu-iron3": { title: "Can You Dig It", artist: "Brian Tyler", youtubeId: "E2CCTfx_jjo" },
  "mcu-tdw": { title: "Thor: The Dark World", artist: "Brian Tyler", youtubeId: "dQAYaM6-L7M" },
  "mcu-ws": { title: "The Winter Soldier", artist: "Henry Jackman", youtubeId: "EBOiJYrmprc" },
  "mcu-gotg": { title: "Come and Get Your Love", artist: "Redbone", youtubeId: "bc0KhhjJP98" },
  "mcu-gotg2": { title: "Mr. Blue Sky", artist: "Electric Light Orchestra", youtubeId: "aQUlA8Hcv4s" },
  "mcu-ultron": { title: "New Avengers", artist: "Danny Elfman", youtubeId: "5aeRFSvfsoo" },
  "mcu-antman": { title: "Ant-Man", artist: "Christophe Beck", youtubeId: "O_5NwVy8L5M" },
  "mcu-cw": { title: "Civil War", artist: "Henry Jackman", youtubeId: "4eaO63O0vD4" },
  "mcu-widow": { title: "Black Widow", artist: "Lorne Balfe", youtubeId: "EAJaSy3XZl0" },
  "mcu-panther": { title: "Black Panther", artist: "Ludwig Göransson", youtubeId: "SKRVqrOp-Uk" },
  "mcu-home": { title: "Spider-Man: Homecoming", artist: "Michael Giacchino", youtubeId: "I42Y1bl5uXs" },
  "mcu-strange": { title: "Doctor Strange", artist: "Michael Giacchino", youtubeId: "O6Gkdme2bck" },
  "mcu-ragnarok": { title: "Immigrant Song", artist: "Led Zeppelin", youtubeId: "P3Y8OWkiUts" },
  "mcu-wasp": { title: "Ant-Man and the Wasp", artist: "Christophe Beck", youtubeId: "J-c-3-jcPKs" },
  "mcu-iw": { title: "Infinity War", artist: "Alan Silvestri", youtubeId: "a10dXUS3ch0" },
  "mcu-endgame": { title: "Portals", artist: "Alan Silvestri", youtubeId: "F_mhWxOjxp4" },
  "mcu-shang": { title: "Shang-Chi", artist: "Joel P West", youtubeId: "C0ArgVsoSsg" },
  "mcu-eternals": { title: "Eternals", artist: "Ramin Djawadi", youtubeId: "ufqIG3JniFg" },
  "mcu-ffh": { title: "Far From Home", artist: "Michael Giacchino", youtubeId: "eoSDzpU5XVE" },
  "mcu-nwh": { title: "Arachnoverture", artist: "Michael Giacchino", youtubeId: "PDmE1thmRFI" },
  "mcu-mom": { title: "Multiverse of Madness", artist: "Danny Elfman", youtubeId: "odZTmtqL8Z8" },
  "mcu-lat": { title: "Thor: Love and Thunder", artist: "Michael Giacchino", youtubeId: "SVyUVXYhIVg" },
  "mcu-wf": { title: "Wakanda Forever", artist: "Ludwig Göransson", youtubeId: "vWeq2Mv-Zds" },
  "mcu-quantum": { title: "Quantumania", artist: "Christophe Beck", youtubeId: "rgfKT4im5ok" },
  "mcu-gotg3": { title: "Dog Days Are Over", artist: "Florence + the Machine", youtubeId: "iWOyfLBYtuU" },
  "mcu-marvels": { title: "The Marvels", artist: "Laura Karpman", youtubeId: "hbT4OzJEetg" },
  "mcu-deadpool": { title: "Like a Prayer", artist: "Madonna", youtubeId: "NdzOv1t8Ie4" },
  "mcu-bnw": { title: "Brave New World", artist: "Laura Karpman", youtubeId: "Z6sfzLzqREw" },
  "mcu-thunder": { title: "Thunderbolts*", artist: "Son Lux", youtubeId: "8-Jzgp1jNiQ" },
  "mcu-ff": { title: "The Fantastic Four", artist: "Michael Giacchino", youtubeId: "_1SdYfVqWps" },
  "fast-1": { title: "Debonaire", artist: "Brian Tyler", youtubeId: "zesHNYS4mOA" },
  "fast-2": { title: "Act a Fool", artist: "Ludacris", youtubeId: "QNMm_XGh8TQ" },
  "fast-4": { title: "Fast & Furious", artist: "Brian Tyler", youtubeId: "8wJt5opJsDA" },
  "fast-5": { title: "Fast Five", artist: "Brian Tyler", youtubeId: "fRq0pQ_BwCw" },
  "fast-6": { title: "We Own It", artist: "2 Chainz, Wiz Khalifa", youtubeId: "tYQ1Okyi3g4" },
  "fast-tokyo": { title: "Tokyo Drift", artist: "Teriyaki Boyz", youtubeId: "aAiAu3-rNEg" },
  "fast-7": { title: "See You Again", artist: "Wiz Khalifa, Charlie Puth", youtubeId: "RgKAFK5djSk" },
  "fast-8": { title: "The Fate of the Furious", artist: "Brian Tyler", youtubeId: "Atnd32m4m-E" },
  "fast-hobbs": { title: "Hobbs & Shaw", artist: "Tyler Bates", youtubeId: "YGZFoigdRMQ" },
  "fast-9": { title: "Fast & Furious 9", artist: "Brian Tyler", youtubeId: "wwFskOQdIG4" },
  "fast-10": { title: "Fast X", artist: "Brian Tyler", youtubeId: "N1KpMVr67ms" },
  "sw-ep1": { title: "Duel of the Fates", artist: "John Williams", youtubeId: "2fte44J8rl0" },
  "sw-ep2": { title: "Across the Stars", artist: "John Williams", youtubeId: "SnkO_Tvd5wk" },
  "sw-ep3": { title: "Battle of the Heroes", artist: "John Williams", youtubeId: "FHuD5y-PZM0" },
  "sw-solo": { title: "Solo", artist: "John Powell", youtubeId: "kJ_OMursypY" },
  "sw-rogue": { title: "Hope", artist: "Michael Giacchino", youtubeId: "RaEzKRngCyY" },
  "sw-anh": { title: "Main Title", artist: "John Williams", youtubeId: "54hoKbTWon4" },
  "sw-esb": { title: "The Imperial March", artist: "John Williams", youtubeId: "u7HF4JG1pOg" },
  "sw-rotj": { title: "Luke and Leia", artist: "John Williams", youtubeId: "GnYb5WfibOg" },
  "sw-tfa": { title: "Rey's Theme", artist: "John Williams", youtubeId: "65As1V0vQDM" },
  "sw-tlj": { title: "The Last Jedi", artist: "John Williams", youtubeId: "U9e5JcKxHaA" },
  "sw-tros": { title: "The Rise of Skywalker", artist: "John Williams", youtubeId: "l-9reMkxTjw" },
  "dceu-ww": { title: "Is She With You", artist: "Hans Zimmer, Junkie XL", youtubeId: "FPfWSW-Zevs" },
  "dceu-ww84": { title: "Themyscira", artist: "Hans Zimmer", youtubeId: "cO01dcHdNTQ" },
  "dceu-mos": { title: "Man of Steel", artist: "Hans Zimmer", youtubeId: "w4OdIOGBW2Q" },
  "dceu-bvs": { title: "Beautiful Lie", artist: "Hans Zimmer, Junkie XL", youtubeId: "8pQSYvYvO5E" },
  "dceu-ss": { title: "Heathens", artist: "Twenty One Pilots", youtubeId: "UprcpdwuwCg" },
  "dceu-bop": { title: "Boss Bitch", artist: "Doja Cat", youtubeId: "ol28OwEJIao" },
  "dceu-jl": { title: "Justice League", artist: "Danny Elfman", youtubeId: "ojyuFzWA0v4" },
  "dceu-aqua": { title: "Aquaman", artist: "Rupert Gregson-Williams", youtubeId: "RTrOxynM2-c" },
  "dceu-shazam": { title: "Shazam!", artist: "Benjamin Wallfisch", youtubeId: "Z3Ry-cuZhoM" },
  "dceu-tss": { title: "So This Is the Famous Suicide Squad", artist: "John Murphy", youtubeId: "51kMlM6YcH4" },
  "dceu-adam": { title: "Black Adam", artist: "Lorne Balfe", youtubeId: "m6PDu887pg4" },
  "dceu-shazam2": { title: "Shazam! Fury of the Gods", artist: "Christophe Beck", youtubeId: "kEgVMr-X7-o" },
  "dceu-flash": { title: "The Flash", artist: "Benjamin Wallfisch", youtubeId: "nO7-tQqWeko" },
  "dceu-beetle": { title: "Blue Beetle", artist: "Bobby Krlic", youtubeId: "MSBRF6K9YS0" },
  "dceu-aqua2": { title: "Aquaman and the Lost Kingdom", artist: "Rupert Gregson-Williams", youtubeId: "HUCLwonc0hw" },
  "fb-1": { title: "Fantastic Beasts", artist: "James Newton Howard", youtubeId: "V8T-JMJSyZQ" },
  "fb-2": { title: "The Crimes of Grindelwald", artist: "James Newton Howard", youtubeId: "uKlHFx27tgY" },
  "fb-3": { title: "The Secrets of Dumbledore", artist: "James Newton Howard", youtubeId: "TujFur1d4TA" },
  "hp-1": { title: "Hedwig's Theme", artist: "John Williams", youtubeId: "a0zG8GR9gWk" },
  "hp-2": { title: "Fawkes the Phoenix", artist: "John Williams", youtubeId: "waFO9mZa-hI" },
  "hp-3": { title: "A Window to the Past", artist: "John Williams", youtubeId: "NCOzImZ4rv8" },
  "hp-4": { title: "Harry in Winter", artist: "Patrick Doyle", youtubeId: "51POnGr6vpw" },
  "hp-5": { title: "Fireworks", artist: "Nicholas Hooper", youtubeId: "M4mURo3icTU" },
  "hp-6": { title: "Harry and Hermione", artist: "Nicholas Hooper", youtubeId: "iDYBJKriEto" },
  "hp-7": { title: "Obliviate", artist: "Alexandre Desplat", youtubeId: "pXT6L_HLG3A" },
  "hp-8": { title: "Lily's Theme", artist: "Alexandre Desplat", youtubeId: "WqSTkBHPxIQ" },
  "hobbit-1": { title: "Misty Mountains", artist: "Howard Shore", youtubeId: "3Dk0meQg6XA" },
  "hobbit-2": { title: "I See Fire", artist: "Ed Sheeran", youtubeId: "2fngvQS_PmQ" },
  "hobbit-3": { title: "The Last Goodbye", artist: "Billy Boyd", youtubeId: "q8ir8rVl2Z4" },
  "lotr-1": { title: "Concerning Hobbits", artist: "Howard Shore", youtubeId: "6dGhy5NzuCE" },
  "lotr-2": { title: "The Riders of Rohan", artist: "Howard Shore", youtubeId: "OzsSZrvIth0" },
  "lotr-3": { title: "Into the West", artist: "Annie Lennox", youtubeId: "-RDuQfSwKfY" },
  "jp-1": { title: "Theme from Jurassic Park", artist: "John Williams", youtubeId: "o1aburRb_2c" },
  "jp-2": { title: "The Lost World", artist: "John Williams", youtubeId: "Yr4OmiKsNe4" },
  "jp-3": { title: "Jurassic Park III", artist: "Don Davis", youtubeId: "i2X25_BFw34" },
  "jw-1": { title: "Welcome to Jurassic World", artist: "Michael Giacchino", youtubeId: "si56PC1JrDw" },
  "jw-2": { title: "Fallen Kingdom", artist: "Michael Giacchino", youtubeId: "t0mGgxrcrQs" },
  "jw-3": { title: "Jurassic World Dominion", artist: "Michael Giacchino", youtubeId: "dK2-SWKJZco" },
  "jw-4": { title: "Jurassic World Rebirth", artist: "Alexandre Desplat", youtubeId: "nUnIAI8Y_LQ" },
  "indy-temple": { title: "Short Round's Theme", artist: "John Williams", youtubeId: "c0_WM9kpngA" },
  "indy-raiders": { title: "The Raiders March", artist: "John Williams", youtubeId: "IgQGqTvd29c" },
  "indy-crusade": { title: "Scherzo for Motorcycle", artist: "John Williams", youtubeId: "5WGUgj_dE_U" },
  "indy-skull": { title: "The Kingdom of the Crystal Skull", artist: "John Williams", youtubeId: "1PtZacw527Q" },
  "indy-dial": { title: "Helena's Theme", artist: "John Williams", youtubeId: "mfwyM16facc" },
  "mi-1": { title: "Mission: Impossible Theme", artist: "Lalo Schifrin, Danny Elfman", youtubeId: "O07WucFwdq8" },
  "mi-2": { title: "I Disappear", artist: "Metallica", youtubeId: "ekZTW2r4vb4" },
  "mi-3": { title: "Mission: Impossible III", artist: "Michael Giacchino", youtubeId: "E5HGZZMOX3U" },
  "mi-4": { title: "Ghost Protocol", artist: "Michael Giacchino", youtubeId: "DypMDlEF_L0" },
  "mi-5": { title: "The Rogue", artist: "Joe Kraemer", youtubeId: "CBfUSYwVuiI" },
  "mi-6": { title: "Fallout", artist: "Lorne Balfe", youtubeId: "FK6_o1tcIj0" },
  "mi-7": { title: "Dead Reckoning", artist: "Lorne Balfe", youtubeId: "FsgxkiBVeKk" },
  "mi-8": { title: "The Final Reckoning", artist: "Lorne Balfe", youtubeId: "z3cpFCO-26Y" },
  "wick-1": { title: "John Wick", artist: "Tyler Bates, Joel J. Richard", youtubeId: "qyEG_ls9xUY" },
  "wick-2": { title: "Plastic Heart", artist: "Ciscandra Nostalghia", youtubeId: "eek_IuyeRFg" },
  "wick-3": { title: "Excommunicado", artist: "Tyler Bates, Joel J. Richard", youtubeId: "zDrwhptzREI" },
  "wick-ballerina": { title: "Ballerina Code", artist: "Le Castle Vania", youtubeId: "nyNfNl3uTvM" },
  "wick-4": { title: "John Wick: Chapter 4", artist: "Tyler Bates, Joel J. Richard", youtubeId: "q-TWmgEASRE" },
  "bond-casino": { title: "You Know My Name", artist: "Chris Cornell", youtubeId: "YnzgdBAKyJo" },
  "bond-quantum": { title: "Another Way to Die", artist: "Jack White, Alicia Keys", youtubeId: "2xh85v1PFMM" },
  "bond-skyfall": { title: "Skyfall", artist: "Adele", youtubeId: "DeumyOzKqgI" },
  "bond-spectre": { title: "Writing's on the Wall", artist: "Sam Smith", youtubeId: "kpm4mX-eLbE" },
  "bond-nttd": { title: "No Time to Die", artist: "Billie Eilish", youtubeId: "BboMpayJomw" },
  "mx-1": { title: "Clubbed to Death", artist: "Rob D", youtubeId: "KwVbcjJYctM" },
  "mx-2": { title: "Matrix Reloaded", artist: "Don Davis", youtubeId: "Emj6jmSaWhQ" },
  "mx-3": { title: "Navras", artist: "Don Davis, Juno Reactor", youtubeId: "oxjhVWrnZO0" },
  "mx-4": { title: "Neo's Theme", artist: "Johnny Klimek, Tom Tykwer", youtubeId: "scU4PvPmqAM" },
  "apes-1": { title: "Rise of the Planet of the Apes", artist: "Patrick Doyle", youtubeId: "mrc7-mkc_AU" },
  "apes-2": { title: "Dawn of the Planet of the Apes", artist: "Michael Giacchino", youtubeId: "HxsoJhDKPcg" },
  "apes-3": { title: "War for the Planet of the Apes", artist: "Michael Giacchino", youtubeId: "EjnmcG3kwkM" },
  "apes-4": { title: "Kingdom of the Planet of the Apes", artist: "John Paesano", youtubeId: "H0niMrSHxtU" },
  "potc-1": { title: "He's a Pirate", artist: "Klaus Badelt, Hans Zimmer", youtubeId: "yRh-dzrI4Z4" },
  "potc-2": { title: "Jack Sparrow", artist: "Hans Zimmer", youtubeId: "lzozXVf1-ss" },
  "potc-3": { title: "Hoist the Colours", artist: "Hans Zimmer", youtubeId: "lNRjt4rCymM" },
  "potc-4": { title: "On Stranger Tides", artist: "Hans Zimmer", youtubeId: "HuHOzKs5RdI" },
  "potc-5": { title: "Dead Men Tell No Tales", artist: "Geoff Zanelli", youtubeId: "PlX9z-hU0To" },
  "max-1": { title: "Mad Max", artist: "Brian May", youtubeId: "1lBmyby3CCs" },
  "max-2": { title: "Mad Max 2", artist: "Brian May", youtubeId: "dvlMZh2370U" },
  "max-3": { title: "We Don't Need Another Hero", artist: "Tina Turner", youtubeId: "HLBXAs2LO8k" },
  "max-furiosa": { title: "Furiosa", artist: "Tom Holkenborg", youtubeId: "Pu7tEpjwlHg" },
  "max-fury": { title: "Brothers in Arms", artist: "Tom Holkenborg", youtubeId: "akggf50-mRI" },
  "hg-0": { title: "The Ballad of Lucy Gray Baird", artist: "Rachel Zegler", youtubeId: "74LYZuxHom0" },
  "hg-1": { title: "The Hunger Games", artist: "James Newton Howard", youtubeId: "rCuJyKHTSsI" },
  "hg-2": { title: "Atlas", artist: "Coldplay", youtubeId: "Lh3TokLzzmw" },
  "hg-3": { title: "The Mockingjay", artist: "James Newton Howard", youtubeId: "x4ww_VyMVcw" },
  "hg-4": { title: "The Hanging Tree", artist: "Jennifer Lawrence", youtubeId: "F3hTW9e20d8" },
  "mv-kong": { title: "Skull Island", artist: "Henry Jackman", youtubeId: "n2B1-Ba39l0" },
  "mv-godzilla": { title: "Godzilla", artist: "Alexandre Desplat", youtubeId: "D1tqRYwZlUo" },
  "mv-kotm": { title: "King of the Monsters", artist: "Bear McCreary", youtubeId: "cD0FeOrK6rk" },
  "mv-gvk": { title: "Godzilla vs. Kong", artist: "Tom Holkenborg", youtubeId: "3EYYUwb_uqs" },
  "mv-gxk": { title: "Godzilla x Kong", artist: "Tom Holkenborg", youtubeId: "fCogkMCuZio" },
  "dune-1": { title: "Paul Atreides", artist: "Hans Zimmer", youtubeId: "2FcZwsbmq3A" },
  "dune-2": { title: "A Time of Quiet Between the Storms", artist: "Hans Zimmer", youtubeId: "igtwOdqboT0" },
  "av-1": { title: "I See You", artist: "Leona Lewis", youtubeId: "3YDz-ftqr1g" },
  "av-2": { title: "Nothing Is Lost", artist: "The Weeknd", youtubeId: "BkeAbsqvtVo" },
  "bm-1": { title: "Molossus", artist: "Hans Zimmer, James Newton Howard", youtubeId: "BdnkbXA_piI" },
  "bm-2": { title: "Why So Serious?", artist: "Hans Zimmer, James Newton Howard", youtubeId: "ofAYX2QkktM" },
  "bm-3": { title: "Rise", artist: "Hans Zimmer", youtubeId: "Fs7FIJHLD48" },
  "al-prometheus": { title: "Prometheus", artist: "Marc Streitenfeld", youtubeId: "OYBC-r3Nj0U" },
  "al-covenant": { title: "Alien: Covenant", artist: "Jed Kurzel", youtubeId: "2g2U9noUk_w" },
  "al-1": { title: "Alien Main Title", artist: "Jerry Goldsmith", youtubeId: "6pnev1fa2bY" },
  "al-romulus": { title: "Alien: Romulus", artist: "Benjamin Wallfisch", youtubeId: "5gLDK9j-QOU" },
  "al-2": { title: "Aliens", artist: "James Horner", youtubeId: "88wUbkRo2jk" },
  "al-3": { title: "Alien 3", artist: "Elliot Goldenthal", youtubeId: "T9FRL6k4YUs" },
  "al-4": { title: "Alien Resurrection", artist: "John Frizzell", youtubeId: "d0r1-EN_J3c" },
  "mcu-wanda": { title: "WandaVision", artist: "Kristen Anderson-Lopez, Robert Lopez", youtubeId: "pktFnMv_pr0" },
  "mcu-fatws": { title: "Louisiana Hero", artist: "Henry Jackman", youtubeId: "KieJPHRHlBc" },
  "mcu-loki": { title: "Loki Theme", artist: "Natalie Holt", youtubeId: "183tEhupiSQ" },
  "mcu-moon": { title: "Moon Knight", artist: "Hesham Nazih", youtubeId: "2uJYMlMdqeI" },
  "mcu-hawkeye": { title: "Hawkeye", artist: "Christophe Beck", youtubeId: "RYG0SIJQbIc" },
  "mcu-echo": { title: "Echo", artist: "Dave Porter", youtubeId: "DHZzoHtyttc" },
  "mcu-agatha": { title: "Agatha All Along", artist: "Kristen Anderson-Lopez, Robert Lopez", youtubeId: "P8u8md-NiHM" },
  "mcu-holiday": { title: "The Guardians of the Galaxy Holiday Special", artist: "John Murphy", youtubeId: "_cFz5Yy7jTM" },
  "mcu-shehulk": { title: "She-Hulk", artist: "Amie Doherty", youtubeId: "9cCYxm_aBEg" },
  "mcu-ironheart": { title: "Ironheart", artist: "Dara Taylor", youtubeId: "scUiCCNwKPo" },
  "mcu-secret": { title: "Secret Invasion", artist: "Kris Bowers", youtubeId: "7coCV7MQyf8" },
  "mcu-ms": { title: "Ms. Marvel", artist: "Laura Karpman", youtubeId: "dGvMqdYWXGA" },
  "mcu-daredevil": { title: "Daredevil: Born Again", artist: "The Newton Brothers", youtubeId: "Ugnw5Q2vXk8" },
  "mcu-bnd": { title: "Spider-Man: Brand New Day", artist: "Michael Giacchino", youtubeId: "W8FtVbKj698" },
  "sw-cw-film": { title: "Star Wars: The Clone Wars", artist: "Kevin Kiner", youtubeId: "sjKjkVmB2Ag" },
  "sw-cw": { title: "Ahsoka's Theme", artist: "Kevin Kiner", youtubeId: "85diX7P_Llg" },
  "sw-badbatch": { title: "The Bad Batch", artist: "Kevin Kiner", youtubeId: "sjKjkVmB2Ag" },
  "sw-kenobi": { title: "Obi-Wan Kenobi", artist: "Natalie Holt", youtubeId: "Q2Tm6PLn70s" },
  "sw-andor": { title: "Andor", artist: "Nicholas Britell", youtubeId: "m0BTjWzYFEA" },
  "sw-mando": { title: "The Mandalorian", artist: "Ludwig Göransson", youtubeId: "2YDKxcdIXBs" },
  "sw-boba": { title: "The Book of Boba Fett", artist: "Ludwig Göransson", youtubeId: "3a0tH0fkvW8" },
  "sw-mando3": { title: "The Mandalorian", artist: "Ludwig Göransson", youtubeId: "2YDKxcdIXBs" },
  "sw-ahsoka": { title: "Ahsoka", artist: "Kevin Kiner", youtubeId: "85diX7P_Llg" },
  "sw-skeleton": { title: "Skeleton Crew", artist: "Mick Giacchino", youtubeId: "MGyOkynVi0E" },
  "sw-grogu": { title: "The Mandalorian and Grogu", artist: "Ludwig Göransson", youtubeId: "DZHshyzeoK0" },
  "dceu-peace": { title: "Do Ya Wanna Taste It", artist: "Wig Wam", youtubeId: "fOdSUtGmxwU" },
  "mv-monarch": { title: "Monarch: Legacy of Monsters", artist: "Leopold Ross", youtubeId: "7KI6S_Eq7pU" },
  "wick-continental": { title: "The Continental", artist: "Raffertie", youtubeId: "a85JJRGJIhk" },
  "dune-prophecy": { title: "Dune: Prophecy", artist: "Volker Bertelmann", youtubeId: "Czil7hiZPR0" },
  "al-earth": { title: "Alien: Earth", artist: "Jeff Russo", youtubeId: "UeHjm5cvUHM" },
  "lotr-rohirrim": { title: "The War of the Rohirrim", artist: "Stephen Gallagher", youtubeId: "uaZpChwvgho" },
  "av-3": { title: "Avatar: Fire and Ash", artist: "Simon Franglen", youtubeId: "PVNP4WS1X8s" },
};
