import type { MovieSource } from "@/lib/types";

export type TimelineInsert = {
  after?: string;
  before?: string;
  item: MovieSource;
};

function poster(imdbId: string) {
  return `https://images.metahub.space/poster/large/${imdbId}/img`;
}

function series(
  id: string,
  title: string,
  year: number,
  runtime: number,
  episodes: number,
  synopsis: string,
  imdbId: string,
  setting: string,
  chapter: string,
  note?: string,
): MovieSource {
  return {
    id,
    title,
    year,
    runtime,
    episodes,
    synopsis,
    poster: poster(imdbId),
    setting,
    chapter,
    tags: [],
    note,
    kind: "series",
  };
}

function movie(
  id: string,
  title: string,
  year: number,
  runtime: number,
  synopsis: string,
  imdbId: string,
  setting: string,
  chapter: string,
  note?: string,
): MovieSource {
  return {
    id,
    title,
    year,
    runtime,
    synopsis,
    poster: poster(imdbId),
    setting,
    chapter,
    tags: [],
    note,
    kind: "movie",
  };
}

export const timelineInserts: Record<string, TimelineInsert[]> = {
  marvel: [
    {
      after: "mcu-endgame",
      item: series(
        "mcu-wanda",
        "WandaVision",
        2021,
        330,
        9,
        "Wanda cria uma sitcom para segurar o luto. Westview inteira entra no episódio, e a feitiçaria deixa de caber no formato.",
        "tt9140560",
        "2023",
        "Multiverso",
        "Três semanas depois de Ultimato.",
      ),
    },
    {
      after: "mcu-wanda",
      item: series(
        "mcu-fatws",
        "Falcão e o Soldado Invernal",
        2021,
        300,
        6,
        "Sam recebe o escudo e descobre que o país já escolheu outro Capitão. Bucky ainda está pagando o século que não viveu.",
        "tt9208876",
        "2024",
        "Multiverso",
        "Cerca de seis meses depois de Ultimato.",
      ),
    },
    {
      after: "mcu-fatws",
      item: series(
        "mcu-loki",
        "Loki",
        2021,
        540,
        12,
        "A variante que fugiu com o Tesseract é recrutada pela TVA. O que ele faz com o tempo explica o multiverso que vem depois.",
        "tt9140554",
        "Fora da linha",
        "Multiverso",
        "As duas temporadas acompanham o Loki que escapa em 2012.",
      ),
    },
    {
      after: "mcu-eternals",
      item: series(
        "mcu-moon",
        "Cavaleiro da Lua",
        2022,
        282,
        6,
        "Steven acorda no meio de uma vida que não é a dele. O avatar de Khonshu cobra a dívida em Londres e no deserto.",
        "tt10234724",
        "2025",
        "Multiverso",
      ),
    },
    {
      after: "mcu-ffh",
      item: series(
        "mcu-hawkeye",
        "Gavião Arqueiro",
        2021,
        264,
        6,
        "Clint só quer o Natal com a família. Kate Bishop acha o traje do Ronin e a cidade ainda tem contas do Blip.",
        "tt10160804",
        "Natal de 2024",
        "Multiverso",
        "Acontece no Natal, antes de Sem Volta para Casa.",
      ),
    },
    {
      after: "mcu-hawkeye",
      item: series(
        "mcu-echo",
        "Eco",
        2024,
        200,
        5,
        "Maya Lopez deixa Nova York e volta para a família. O poder que ela herdou não fica em silêncio.",
        "tt13966962",
        "Depois de Gavião Arqueiro",
        "Multiverso",
      ),
    },
    {
      after: "mcu-mom",
      item: series(
        "mcu-agatha",
        "Agatha Desde Sempre",
        2024,
        360,
        9,
        "Sem magia, Agatha percorre a Estrada das Bruxas. O que Wanda deixou para trás ainda tem nome e voz.",
        "tt15571732",
        "Depois do Multiverso da Loucura",
        "Multiverso",
      ),
    },
    {
      after: "mcu-lat",
      item: movie(
        "mcu-holiday",
        "Guardiões da Galáxia: Especial de Festas",
        2022,
        44,
        "Mantis e Drax tentam dar a Peter o Natal que a Terra levou. A árvore é roubada, o presente é a equipe.",
        "tt13623136",
        "Entre Amor e Trovão e Vol. 3",
        "Multiverso",
        "Especial situado antes de Guardiões da Galáxia Vol. 3.",
      ),
    },
    {
      after: "mcu-holiday",
      item: series(
        "mcu-shehulk",
        "Mulher-Hulk: Defensora de Heróis",
        2022,
        270,
        9,
        "Jennifer Walters vira advogada e Hulk no mesmo processo. Wong, o Abominável e um escritório inteiro entram na pauta.",
        "tt10857160",
        "2025",
        "Multiverso",
      ),
    },
    {
      after: "mcu-wf",
      item: series(
        "mcu-ironheart",
        "Coração de Ferro",
        2025,
        270,
        6,
        "Riri Williams constrói a armadura no lugar de quem já não pode vesti-la. Chicago cobra o preço do gênio.",
        "tt13623126",
        "Depois de Wakanda para Sempre",
        "Multiverso",
      ),
    },
    {
      after: "mcu-gotg3",
      item: series(
        "mcu-secret",
        "Invasão Secreta",
        2023,
        246,
        6,
        "Fury volta à Terra e não sabe mais quem é humano. Os Skrulls já sentaram à mesa.",
        "tt13157618",
        "Antes de As Marvels",
        "Multiverso",
      ),
    },
    {
      after: "mcu-secret",
      item: series(
        "mcu-ms",
        "Ms. Marvel",
        2022,
        276,
        6,
        "Kamala Khan desenha o herói que quer ser e descobre que o bracelete da família já era uma arma.",
        "tt10857164",
        "Antes de As Marvels",
        "Multiverso",
        "A origem de Kamala, imediatamente antes de As Marvels.",
      ),
    },
    {
      after: "mcu-thunder",
      item: series(
        "mcu-daredevil",
        "Demolidor: Renascido",
        2025,
        450,
        9,
        "Matt Murdock tenta uma vida sem o capuz. Wilson Fisk escolhe o outro caminho: a prefeitura.",
        "tt18923754",
        "2025–2026",
        "Multiverso",
      ),
    },
    {
      after: "mcu-ff",
      item: movie(
        "mcu-bnd",
        "Homem-Aranha: Um Novo Dia",
        2026,
        145,
        "Peter patrulha uma cidade que esqueceu o nome dele. O novo dia cobra um poder que ele ainda não sabe segurar.",
        "tt22084616",
        "Depois de Sem Volta para Casa",
        "Multiverso",
        "Lançado em julho de 2026. Continua a vida de Peter depois do feitiço.",
      ),
    },
  ],
  "star-wars": [
    {
      after: "sw-ep2",
      item: movie(
        "sw-cw-film",
        "Star Wars: A Guerra dos Clones",
        2008,
        98,
        "Anakin recebe uma aprendiz que ninguém pediu. Ahsoka entra na guerra no mesmo dia em que Jabba exige o filho de volta.",
        "tt1185834",
        "22 ABY",
        "A queda da República",
        "Filme de animação situado logo após o Episódio II.",
      ),
    },
    {
      after: "sw-cw-film",
      item: series(
        "sw-cw",
        "Star Wars: A Guerra dos Clones",
        2008,
        2926,
        133,
        "A guerra se espalha por sete temporadas. Ahsoka deixa a Ordem, Maul volta, e a República já é o Império sem o nome.",
        "tt0458290",
        "22–19 ABY",
        "A queda da República",
        "A série inteira fica entre o filme de 2008 e o Episódio III.",
      ),
    },
    {
      after: "sw-ep3",
      item: series(
        "sw-badbatch",
        "Star Wars: The Bad Batch",
        2021,
        1034,
        47,
        "Um esquadrão de clones defeituosos recusa a Ordem 66. O Império nasce enquanto eles procuram um lugar que não seja a guerra.",
        "tt12708542",
        "19 ABY",
        "A era do Império",
        "Começa no fim do Episódio III.",
      ),
    },
    {
      after: "sw-solo",
      item: series(
        "sw-kenobi",
        "Obi-Wan Kenobi",
        2022,
        270,
        6,
        "Dez anos depois da queda, Kenobi vigia Luke no deserto. A Inquisidora e Vader encontram o mestre que ainda não morreu.",
        "tt8466564",
        "9 ABY",
        "A era do Império",
        "Depois de Han Solo e antes de Andor.",
      ),
    },
    {
      after: "sw-kenobi",
      item: series(
        "sw-andor",
        "Andor",
        2022,
        1080,
        24,
        "Cassian ainda não é um herói da Aliança. A rebelião é furtiva, cara, e começa anos antes dos planos da Estrela da Morte.",
        "tt9253284",
        "5–0 ABY",
        "A era do Império",
        "As duas temporadas terminam na porta de Rogue One.",
      ),
    },
    {
      after: "sw-rotj",
      item: series(
        "sw-mando",
        "O Mandaloriano: Temporadas 1 e 2",
        2019,
        560,
        16,
        "Din Djarin aceita um trabalho e fica com a criança. O Império ainda tem laboratórios, e o Jedi que chega no fim muda a galáxia.",
        "tt8111088",
        "9 DBY",
        "A Nova República",
      ),
    },
    {
      after: "sw-mando",
      item: series(
        "sw-boba",
        "O Livro de Boba Fett",
        2021,
        280,
        7,
        "Boba toma o trono de Jabba e descobre que Tatooine não se herda. Grogu escolhe o capacete em vez do templo.",
        "tt13668894",
        "9 DBY",
        "A Nova República",
        "Entre a 2ª e a 3ª temporada de O Mandaloriano.",
      ),
    },
    {
      after: "sw-boba",
      item: series(
        "sw-mando3",
        "O Mandaloriano: 3ª temporada",
        2023,
        320,
        8,
        "Din volta a Mandalore com Grogu. O planeta ainda está em cinzas, e o credo precisa de um povo para existir.",
        "tt8111088",
        "9 DBY",
        "A Nova República",
      ),
    },
    {
      after: "sw-mando3",
      item: series(
        "sw-ahsoka",
        "Ahsoka",
        2023,
        320,
        8,
        "Ahsoka procura o mapa para Ezra e Thrawn. O que volta de outra galáxia não vem sozinho.",
        "tt13622776",
        "9 DBY",
        "A Nova República",
      ),
    },
    {
      after: "sw-ahsoka",
      item: series(
        "sw-skeleton",
        "Star Wars: Skeleton Crew",
        2024,
        280,
        8,
        "Quatro crianças saem de um planeta pacífico e descobrem que a galáxia ainda tem piratas. A Nova República fica longe demais.",
        "tt20600980",
        "Por volta de 9 DBY",
        "A Nova República",
      ),
    },
    {
      after: "sw-skeleton",
      item: movie(
        "sw-grogu",
        "O Mandaloriano e Grogu",
        2026,
        132,
        "Din e Grogu seguem juntos numa galáxia que ainda não está em paz. A Nova República pede um caçador que já escolheu a criança.",
        "tt30825738",
        "Depois da 3ª temporada",
        "A Nova República",
        "Lançado em 2026, antes da trilogia sequência.",
      ),
    },
  ],
  dceu: [
    {
      after: "dceu-tss",
      item: series(
        "dceu-peace",
        "Pacificador",
        2022,
        720,
        16,
        "Christopher Smith sai do hospital achando que ainda é herói. A equipe e a águia discordam, e a missão seguinte também.",
        "tt13146488",
        "Depois de O Esquadrão Suicida",
        "Crepúsculo",
        "As temporadas seguem o filme de 2021, não o Esquadrão de 2016.",
      ),
    },
  ],
  monsterverse: [
    {
      after: "mv-godzilla",
      item: series(
        "mv-monarch",
        "Monarch: Legado de Monstros",
        2023,
        480,
        10,
        "Meio século de Monarch, contado em duas gerações. Godzilla já atravessou São Francisco. A agência ainda mente sobre o resto.",
        "tt17220216",
        "1950 e 2015",
        "O despertar",
        "A linha de 2015 fica depois de Godzilla e antes de Rei dos Monstros.",
      ),
    },
  ],
  "john-wick": [
    {
      before: "wick-1",
      item: series(
        "wick-continental",
        "O Continental",
        2023,
        210,
        3,
        "Em 1975, o hotel de Nova York ainda está sendo tomado. Winston e Charon aprendem as regras antes de Wick existir.",
        "tt6486762",
        "1975",
        "Antes do jogo",
        "Prequela situada décadas antes de John Wick.",
      ),
    },
  ],
  duna: [
    {
      before: "dune-1",
      item: series(
        "dune-prophecy",
        "Duna: A Profecia",
        2024,
        360,
        6,
        "Dez mil anos antes de Paul, as irmãs que vão virar a Bene Gesserit disputam o império e a verdade. A especiaria ainda é um rumor.",
        "tt10466872",
        "Milênios antes",
        "A irmandade",
        "Abre a cronologia, muito antes da casa Atreides.",
      ),
    },
  ],
  alien: [
    {
      after: "al-covenant",
      item: series(
        "al-earth",
        "Alien: Earth",
        2025,
        400,
        8,
        "Em 2120, uma nave cai numa cidade das corporações. Wendy e os híbridos encontram a espécie dois anos antes da Nostromo.",
        "tt13623632",
        "2120",
        "A Terra",
        "Entre Covenant e o Oitavo Passageiro.",
      ),
    },
  ],
  "terra-media": [
    {
      before: "hobbit-1",
      item: movie(
        "lotr-rohirrim",
        "O Senhor dos Anéis: A Guerra dos Rohirrim",
        2024,
        134,
        "Helm Mão de Ferro enfrenta a invasão de Rohan séculos antes de Bilbo. O Abismo da Helm ganha o nome nesta guerra.",
        "tt14824600",
        "2758–2759 T.E.",
        "Rohan",
        "Quase dois séculos antes de O Hobbit.",
      ),
    },
  ],
  avatar: [
    {
      after: "av-2",
      item: movie(
        "av-3",
        "Avatar: Fogo e Cinzas",
        2025,
        197,
        "A família Sully ainda está nos recifes quando o fogo chega a Pandora. O povo das cinzas não negocia com a floresta.",
        "tt1757678",
        "Depois do caminho da água",
        "O fogo",
        "Lançado em dezembro de 2025.",
      ),
    },
  ],
};
